---
title: "How to use this package - A basic example"
author: "Christoph Burow"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    number_sections: no
    toc: yes
    toc_depth: 6
vignette: >
  %\VignetteIndexEntry{How to use this package - A basic example (code only)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Preparation

```{r}
library(gammaSpec)
```


## Importing a measured spectrum

```{r, eval=FALSE}
spec <- read_SPE(file = "path/to/my/file.Spe")
str(spec, max.level = 2)
```

```{r, echo = FALSE}
file <- system.file("extdata", "Nievenheim_DORNIE_1.spe", package = "gammaSpec")
spec <- read_SPE(file)
str(spec, max.level = 2)
```

## Estimating the gamma dose rate

```{r, fig.align='center', fig.keep='all', fig.show='hold', fig.width=7}
res <- calc_DoseRate(data = spec,
                     energy.min = 500,
                     energy.max = 2600,
                     background.correction = TRUE,
                     plot = TRUE,
                     plot.combine = FALSE,
                     app = FALSE,
                     cex = 0.8)
```

